remove sh/ bash utils

diff --git a/bin/json-format b/bin/json-format
--- a/bin/json-format
+++ b/bin/json-format
@@ -1,7 +1,13 @@
 #!/bin/sh
 # Pretty prints JSON text to the command line.
 . "$S_DOTFILE_ROOT"/shell_profile/functions.sh
-. "$S_DOTFILE_ROOT"/sh/cli.sh
+
+error()             { printf '[ERROR]: %s\n' "$*" >&2; }
+exit_with_message() { code="$1"; shift; error "$@"; exit "${code:-1}"; }
+set_verbose()       { export VERBOSE="${1:-1}"; }
+is_verbose()        { [ "${VERBOSE:-0}" = "1" ]; }
+verbose()           { [ "${VERBOSE:-0}" = "1" ] && echo "$@"; return 0; }
+print_action()      { echo "$@"; }
 
 print_help() {
   echo "Pretty print JSON text from stdin or a file to the terminal."
